import { library } from "@fortawesome/fontawesome-svg-core";
import {
  faHome,
  faUser,
  faUserGraduate,
  faSearch,
  faPlus,
  faCompressAlt,
  faExpandAlt,
  faFolder,
  faBook,
  faEdit,
  faBars,
  faFilter,
  faStickyNote,
  faQuestion,
  faLayerGroup,
  faCalendarAlt,
  faEllipsisH,
  faSignOutAlt,
  faMinusCircle,
  faTimes,
  faCheckSquare,
  faDotCircle,
  faParagraph,
  faClone,
  faEllipsisV,
  faCaretDown,
  faCaretUp,
  faCheck,
  faCog,
  faInfo
} from "@fortawesome/free-solid-svg-icons";
import { FontAwesomeIcon } from "@fortawesome/vue-fontawesome";

library.add(
  faHome,
  faUser,
  faUserGraduate,
  faSearch,
  faPlus,
  faCompressAlt,
  faExpandAlt,
  faFolder,
  faBook,
  faEdit,
  faBars,
  faFilter,
  faStickyNote,
  faQuestion,
  faLayerGroup,
  faCalendarAlt,
  faEllipsisH,
  faSignOutAlt,
  faMinusCircle,
  faTimes,
  faCheckSquare,
  faDotCircle,
  faParagraph,
  faClone,
  faEllipsisV,
  faCaretDown,
  faCaretUp,
  faCheck,
  faCog,
  faInfo
);

export { FontAwesomeIcon };
